volumes:
  pg_data:

services:
  db:
    image: postgres:18
    restart: on-failure
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 3210:8080
