# SPDX-FileCopyrightText: 2026 Alper Çelik <alper@alper-celik.dev>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-License-Identifier: Apache-2.0

name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: nix develop .#ci --command bash --noprofile --norc -eo pipefail {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        background: true

      - name: InstallNix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v17
        with:
          name: projectbook
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - wait-all:

      - name: Install Deps
        run: nix develop .#ci --command ls

      - name: Run ReUse Lint
        background: true
        run: just reuse

      - name: Dotnet Ci
        background: true
        run: |
          just dotnet-ci

      - wait-all:
