# SPDX-FileCopyrightText: 2026 Alper Çelik <alper@alper-celik.dev>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-License-Identifier: Apache-2.0

name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: nix develop .#ci --command bash --noprofile --norc -eo pipefail {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/cache@v6
        id: nixcache
        background: true
        env:
          ZSTD_CLEVEL: "1"
        with:
          path: ~/nix-vol
          key: ${{ runner.os }}-nix-${{ hashFiles('**/flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-${{ hashFiles('**/flake.lock') }}

      - uses: actions/cache@v6
        background: true
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - wait-all:

      - name: prepare nix vol
        shell: bash
        run: |
          if [ ! -f ~/nix-vol ]; then
            fallocate -l 3G ~/nix-vol 
            sudo mkfs.btrfs ~/nix-vol
          fi;
          sudo mount -o compress=zstd:4 -m $HOME/nix-vol /nix;

      - name: clear nix vol
        uses: gacts/run-and-post-run@v1.4.4
        if: steps.nixcache.outputs.cache-hit != 'true'
        with:
          post-shell: bash
          post: |
            sudo systemctl stop nix-daemon.service nix-daemon.socket
            sudo fuser -m /nix -v
            sudo fuser -m /nix -v -k
            sudo fuser -m /nix -v
            sudo umount /nix

      - name: InstallNix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v17
        with:
          name: projectbook
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - wait-all:

      - name: Install Deps
        if: steps.nixcache.outputs.cache-hit != 'true'
        run: nix develop .#ci --command ls

      - name: Run ReUse Lint
        background: true
        run: just reuse-check

      - name: Dotnet Ci
        background: true
        run: |
          just ci-dotnet

      - wait-all:
